import translationsData from "./translations-data.json";

export type Translations = Record<string, string>;

// Generated by scripts/sync-translations.py from translations.py — run
// `npm run sync:translations` after editing translations.py to refresh
// this file. Bundled locally instead of fetched from the backend so
// pages don't wait on a network round trip (and a possibly cold-starting
// serverless backend) just to show static UI strings.
const LOCAL_TRANSLATIONS = translationsData as Record<string, Translations>;

export async function fetchTranslations(lang: string): Promise<Translations> {
  return LOCAL_TRANSLATIONS[lang] ?? LOCAL_TRANSLATIONS["en"] ?? {};
}

// Ported from app/core/config.py's CONVERSATION_TAGS (repo root) — a
// small, fixed, rarely-changing design constant, not user data, so it's
// duplicated here rather than adding a second backend endpoint just for
// it. Keep in sync by hand if that dict ever changes. Labels for these
// keys come from the /translations/{lang} endpoint (`tag_<key>`), not
// from here.
export const CONVERSATION_TAGS: Record<string, { icon: string; color: string }> = {
  family: { icon: "fa-people-roof", color: "#5B8DEF" },
  friends: { icon: "fa-user-friends", color: "#F2CC8F" },
  health: { icon: "fa-heart-pulse", color: "#5B9A7D" },
  daily: { icon: "fa-sun", color: "#98A2B3" },
  important: { icon: "fa-star", color: "#E07A5F" },
};
